# <font color = 'dodgerred'>**Solution HW1** </font>



In [ ]:
import torch
import time

# <font color = 'dodgerred'>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [ ]:
my_tensor = torch.zeros((5,3))

In [ ]:
my_tensor.shape

torch.Size([5, 3])

In [ ]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".
my_tensor[0,2], my_tensor[2,0] = 10, 100

In [ ]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = 'dodgerred'>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [ ]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
x = x.view(6, 4).permute(1,0)
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = 'dodgerred'>**Q3: Slice tensor (1 Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [ ]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [ ]:
x.shape

torch.Size([3, 5])

In [ ]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = x[-1,:]
last_row

tensor([11, 12, 13, 14, 15])

In [ ]:
# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:, 3]
fourth_column

tensor([ 4,  8, 14])

In [ ]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = x[0:3, 0:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [ ]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = x[0::2, 0::2]
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = 'dodgerred'>**Q4 -Normalize Function (1 Point)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [ ]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [ ]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [ ]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [ ]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [ ]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [ ]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = x.mean(axis=0)

  # Calculate the standard deviation along each column
  std = x.std(axis=0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x - mean) / std

  return y  # Return the normalized matrix



In [ ]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [ ]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

In [ ]:
Z.std(axis = 0)

tensor([1., 1., 1., 1.])

# <font color = 'dodgerred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [ ]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', id(A))
A.add_(5)
print('Memory address of A after in-place addition:', id(A))
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', id(B))
B = B.add(5)
print('Memory address of B after out-of-place addition:', id(B))
print('B after out-of-place addition:', B)


Original memory address of A: 134234535193120
Memory address of A after in-place addition: 134234535193120
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 134237874698208
Memory address of B after out-of-place addition: 134234535018256
B after out-of-place addition: tensor([ 9, 10, 11])


**Provide Explanation for above question here :**

The in-place addition operation `add_` modifies the tensor 'A' directly, without creating a new tensor. Therefore, the memory address before and after the operation remains the same, indicating that the original tensor is modified in place.

The out-of-place addition operation `add` creates a new tensor with the result of the addition. As a result, the memory address of 'B' changes after the operation, indicating that a new tensor is created and assigned to the variable 'B'. The original tensor is not modified, and the result is stored in a new memory location.

In summary, in-place operations modify the original tensor and do not change the memory address, while out-of-place operations create a new tensor and hence have a different memory address post-operation.

# <font color = 'dodgerred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [ ]:
X = torch.ones(3, 1)
Y = torch.arange(1, 4).view(1, 3)
print('Original shapes:', X.shape, Y.shape)
result = X + Y
print('Result:', result)
print('Result shape:', result.shape)



Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**

In the code snippet, tensors `X` and `Y` are added using broadcasting. Here's an explanation of how broadcasting works in this operation:

1. **Initial Shapes**:
   - `X` has a shape of `(3, 1)`.
   - `Y` has a shape of `(1, 3)`.

2. **Broadcasting Rules**:
   - PyTorch compares the shapes of `X` and `Y` element-wise from the last dimension:
     - The dimensions are compatible because one of the dimensions is `1`.
   - The tensor with the smaller dimension (in this case, both `X` and `Y`) is virtually expanded to match the larger dimension without copying data.
   
3. **Internal Shape Adjustment**:
   - `X` is broadcasted to a shape of `(3, 3)` by repeating its columns.
   - `Y` is broadcasted to a shape of `(3, 3)` by repeating its rows.

4. **Result of the Addition**:
   - The element-wise addition is performed on the broadcasted tensors.
   - The resulting tensor has a shape of `(3, 3)`, and each element is the sum of the corresponding elements of `X` and `Y`.

5. **Conclusion**:
   - Broadcasting allows for element-wise operations on tensors of different shapes by virtually expanding the smaller tensor along the dimension with size `1`.
   - The operation does not involve actual data duplication, which makes broadcasting memory-efficient.

# <font color = 'dodgerred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [ ]:
M1 = torch.tensor([[1, 2], [3, 4]])
M2 = torch.tensor([[5, 6], [7, 8]])
product = torch.matmul(M1, M2)
print('Matrix multiplication result:', product)

V1 = torch.tensor([1, 2, 3])
V2 = torch.tensor([4, 5, 6])
dot_product = torch.dot(V1, V2)
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[19, 22],
        [43, 50]])
Dot product: tensor(32)


# <font color = 'dodgerred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [ ]:
T = torch.rand(2, 3, 4)
T_view = T.view(3, 8)
print('T_view shape:', T_view.shape)

T_reshape = T.reshape(4, 2, 3)
print('T_reshape shape:', T_reshape.shape)

T_permute = T.permute(2, 1, 0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**
The `view` and `reshape` methods in PyTorch are used to change the shape of a tensor without changing its data. Here's the concise explanation of the difference between them:

- **`view`**:
  - Returns a new tensor with the same data as the original tensor but with a different shape.
  - Requires the new shape to be compatible with the original shape and the tensor to be contiguous in memory. If the tensor is not contiguous, it will fail (you may need to call `.contiguous()` before calling `.view()`).
  - It's a low-level method in terms of memory usage, as it operates directly on the original tensor's memory.

- **`reshape`**:
  - Also returns a new tensor with the same data as the original tensor but with a different shape.
  - Similar to `view`, but it can work with non-contiguous tensors by internally handling the memory layout if necessary.
  - If the tensor is contiguous, `reshape` and `view` will provide the same functionality. If not, `reshape` may return a copy of the tensor to ensure the requested shape.

In summary, while both `view` and `reshape` can be used to change the shape of a tensor, `reshape` is more flexible as it can handle non-contiguous tensor layouts, potentially at the cost of performance if a copy of the tensor needs to be made.

# <font color = 'dodgerred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [ ]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 = torch.cat((C1, C2), dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 = torch.cat((C1, C2), dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked = torch.stack((C1, C2), dim = 0)
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**

The difference between stacking and concatenating tensors in PyTorch lies in how the tensors are combined:

- **Concatenating**:
  - Combines tensors along an existing dimension.
  - The tensors to be concatenated must have the same shape in all dimensions except for the dimension along which they are concatenated.
  - The result has the same number of dimensions as the original tensors, but the size of the dimension along which they are concatenated is the sum of the sizes of that dimension in each tensor.
  - Example: Concatenating two tensors of shape `(2, 3)` along dimension 0 results in a tensor of shape `(4, 3)`, and along dimension 1 results in a tensor of shape `(2, 6)`.

- **Stacking**:
  - Combines tensors along a new dimension.
  - All tensors to be stacked must have the same shape.
  - The resulting tensor has one more dimension than the original tensors, with the size of the new dimension equal to the number of tensors stacked.
  - Example: Stacking two tensors of shape `(2, 3)` results in a tensor of shape `(2, 2, 3)`, with the new dimension added at the beginning (dimension 0).

In summary, concatenation merges tensors along an existing axis, while stacking adds a new dimension to the tensor and stacks along it.


# <font color = 'dodgerred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [ ]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n', D[D > 0.5])

second_fourth_rows = D[1::2]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 = D[:3, :3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)


Elements greater than 0.5:
 tensor([0.5396, 0.7725, 0.6434, 0.8961, 0.8104, 0.5072, 0.5674, 0.6243, 0.5790,
        0.8664, 0.7271, 0.7643, 0.6259, 0.5248, 0.5040, 0.6147, 0.8272, 0.5612,
        0.5318, 0.6680])

Second and fourth rows:
 tensor([[0.8104, 0.1105, 0.5072, 0.2074, 0.5674, 0.6243],
        [0.2082, 0.0723, 0.6259, 0.4635, 0.3203, 0.5248],
        [0.8272, 0.0098, 0.5612, 0.4052, 0.5318, 0.6680]])

Top-left 3x3 block:
  tensor([[0.5396, 0.2973, 0.7725],
        [0.8104, 0.1105, 0.5072],
        [0.4442, 0.4958, 0.5790]])


# <font color = 'dodgerred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [ ]:
G = torch.arange(0, torch.pi, torch.pi/4)
print('G:', G)
print('Sine of G:', torch.sin(G))
print('Cosine of G:', torch.cos(G))
print('Tangent of G:', torch.tan(G))
print('Natural logarithm of G:', torch.log(G))
print('Exponential of G:', torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562])
Sine of G: tensor([0.0000, 0.7071, 1.0000, 0.7071])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507])


# <font color = 'dodgerred'>Q12: **Tensor Reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [ ]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:', torch.sum(H))
print('Shape after Sum of H:', torch.sum(H).shape,  end = "\n\n")

print('Sum of H along dimension 0:', torch.sum(H, dim=0),)
print('Shape after sum of H along dimension 0:', torch.sum(H, dim=0).shape,  end = "\n\n")

print('Sum of H along dimension 1:', torch.sum(H, dim=1))
print('Shape after sum of H along dimension 1:', torch.sum(H, dim=1).shape)


H: tensor([[0.1203, 0.5088],
        [0.2164, 0.0863],
        [0.2356, 0.6817]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(1.8491)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([0.5723, 1.2768])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([0.6291, 0.3027, 0.9172])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**

Observations regarding how the shape changes after each operation:

1. **Original Tensor `H` (3x2):**
   - The tensor `H` is initialized with random values and has a shape of (3, 2). This means it has 3 rows and 2 columns.

2. **Sum of `H`:**
   - When you compute `torch.sum(H)`, it calculates the sum of all elements in the tensor. As a result, it returns a single scalar value (a 0-dimensional tensor).
   - **Observation**: The shape changes from (3, 2) to an empty shape `torch.Size([])`, indicating a scalar.

3. **Sum of `H` along dimension 0:**
   - When you compute `torch.sum(H, dim=0)`, it sums the elements of `H` along dimension 0 (vertically). This means each element in the resulting tensor is the sum of the elements in each column of `H`.
   - **Observation**: The shape changes from (3, 2) to (2,), indicating that the sum is computed for each column, and the number of rows is reduced to a single value representing the sum of each column.

4. **Sum of `H` along dimension 1:**
   - When you compute `torch.sum(H, dim=1)`, it sums the elements of `H` along dimension 1 (horizontally). This means each element in the resulting tensor is the sum of the elements in each row of `H`.
   - **Observation**: The shape changes from (3, 2) to (3,), indicating that the sum is computed for each row, and the number of columns is reduced to a single value representing the sum of each row.

In summary, when you perform a sum operation along a specific dimension, the shape of the tensor is reduced along that dimension. For a sum over the entire tensor, you get a scalar. For a sum along a specific dimension, that dimension is collapsed to a single value representing the sum along that dimension. The overall rank of the tensor (number of dimensions) is reduced by one for each dimension you sum over.

# <font color = 'dodgerred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [ ]:
# Solution for Q16
I = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)
print('I:', I)
I_int = I.to(dtype=torch.int)
print('I converted to int:', I_int)
# Explanation: It's necessary to be cautious about data types when converting between float and int
# to avoid losing precision or information.


I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**

Being cautious about the data type of tensors is important in various scenarios due to the different ways that data types handle numerical precision, computation speed, and memory usage. Here are some specific scenarios where careful consideration of tensor data types is crucial:

1. **Loss of Precision**: When converting from a type with higher precision to lower precision (e.g., from `float` to `int`), there is a loss of precision. Decimal parts are truncated when converting from a floating-point type to an integer type. This can lead to loss of critical information, especially if the decimals are significant for the calculations or results.

2. **Overflow and Underflow**: Certain operations might result in numbers that are too large or too small to be represented in the chosen data type, leading to overflow or underflow. For instance, integer types have a fixed range, and exceeding this range might result in unexpected behavior or errors.

3. **Compatibility with Frameworks and Functions**: Some PyTorch functions and neural network layers expect inputs of a certain data type. Using the incorrect data type might lead to errors or inefficient computation. For example, convolution layers in a neural network might expect floating-point weights for gradient computations.

4. **Memory Usage**: Data types with higher precision (like `float64`) consume more memory compared to lower precision types (like `float32` or `int`). In scenarios where you're working with large datasets or models, choosing a more memory-efficient data type can be crucial to prevent running out of memory, especially on limited resources like GPUs.

5. **Computational Speed**: Operations on lower precision data types are generally faster. This is particularly noticeable when working with GPUs, as they are optimized for high-speed computation on lower precision data. For instance, using `float16` (half-precision) can speed up training neural networks without significantly affecting the model's performance.

6. **Gradient Computations in Neural Networks**: When training neural networks, the choice of data type affects the precision of gradient computations. Lower precision might lead to inadequate learning or failure to converge, as small gradient values may vanish or not be captured accurately.

7. **Quantization and Model Deployment**: When deploying models, especially on edge devices with limited resources, model quantization (reducing the precision of the model's parameters) is common. Careful management of data types is crucial here to balance between performance, accuracy, and resource usage.

In each of these scenarios, understanding the implications of tensor data types helps in making informed decisions, ensuring the accuracy of computations, and optimizing performance and resource usage.

# <font color = 'dodgerred'>**Question 14. Speedtest for vectorization - 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024))
B= torch.randn((1024, 1024))

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.01940011978149414 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(C.shape[1]):
  C[:,i] = torch.mv(A, B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.2724425792694092 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

for i in range(C.shape[0]):
  for j in range(C.shape[1]):
    C[i,j] = torch.dot(A[i], C[j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 14.729571104049683 seconds


# <font color = 'dodgerred'>**Question 4 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [ ]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.10759520530700684 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(C.shape[1]):
  C[:,i] = torch.mv(A, B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.08559584617614746 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(C.shape[0]):
  for j in range(C.shape[1]):
    C[i,j] = torch.dot(A[i], C[j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 32.53825521469116 seconds
